#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
#*  AniCLASS input parameter file  *
#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

# This file contains the input parameters required by AniCLASS to compute 
# the deterministic multipoles from nearly-isotropic Bianchi models.
###############################################################################

# -----------------
# 1 - Choosing Bianchi
# -----------------

# 1.1 - hierarchy: method to compute the Boltzmann hierarchy
# The only method modified to accommodate Bianchi models is tam (Total Angular Momentum)
hierarchy = tam

# 1.2 - statistics: whether the modes are deterministic or not
# Must be set to non_stochastic
statistics = non_stochastic

# 1.3 - non_stochastic_type
# Must be set to bianchi
non_stochastic_type = bianchi 

###############################################################################


# ---------------------
# 2. Output parameters
# ---------------------

# 2.1 - output:
# Can be set to tCl (temperature), pCl (polarization)
# Note: although the name convention follows standard CLASS, AniCLASS outputs the multipoles (alms).
# Since the effects of nearly-isotropic Bianchi models are deterministic, 
# there is no power spectrum associated with these perturbations.
output = tCl,pCl
#output = tCl
#output = pCl

# 2.2 - modes: t (tensor), v (vector). Scalar modes are not implemented.
modes = t, v
# modes = t
# modes = v

# 2.3 - Cosmological parameters are set following CLASS convention
# Please check the file explanatory.ini for details
# The curvature parameter is especially important because it is required to define the
# Bianchi model.
# Note that the only Bianchi model with negative Omega_k is IX
Omega_k = 0.01
z_reio = 7.6711  # Example: redshift of reionization

# 2.4 - gauge: synchronous or newtonian
gauge = synchronous
#gauge = newtonian

# 2.5 - ic_v: initial condition for vector modes
# Options: iso (neutrino quadrupole isocurvature), oct (neutrino octopole isocurvature)
# See [TODO: insert arXiv link] for details.
ic_v = iso
#ic_v = oct

# 2.6 - k_output_values: Fourier modes to output
# Note that the relation between k and the spiraling length (\ell_s) in nearly-isotropic Bianchi models is
# k = 2 / \ell_s (for tensor modes)
# k = 1 / \ell_s (for vector modes)
k_output_values = 0.001, 0.002
#k_output_values = 0.001

# 2.7 - l_max: maximum multipole to compute in the Line-of-Sight integration
l_max_vectors = 100
l_max_tensors = 100

# 2.8 - multipole_normalization:
# Options: observable or tam
# See [TODO: arxiv link] for details.
multipole_normalization = observable
#multipole_normalization = tam

# 2.9 - non_stochastic_format:
# Options: 
# class: dense output with only non-zero multipoles (a_{\ell 1} for vectors and a_{\ell 2} for tensors)
# healpix_alm: format for Healpix usage
non_stochastic_format = class
#non_stochastic_format = healpix_alm

# 2.10 - Other output options (see explanatory.ini for more)
# Examples:
write_background = yes
write_thermodynamics = yes


###############################################################################

# --------------------------
# 3. Precision parameters
# --------------------------

# 3.1 - Truncation multipoles for the Boltzmann hierarchy
# Note that the default values are too small and lead to propagating errors for the Bianchi case
# Use the values below for reliable results in Bianchi runs.

l_max_g_vec = 30          # Temperature truncation (vector)
l_max_pol_g_vec = 30      # Polarization truncation (vector)
l_max_ur_vec = 30         # Ultra-relativistic species (vector)

l_max_g_ten = 30          # Temperature truncation (tensor)
l_max_pol_g_ten = 30      # Polarization truncation (tensor)
l_max_ur_ten = 30         # Ultra-relativistic species (tensor)

# 3.2 - radiation_streaming_approximation:
# Must be set to 3 (no approximation) for Bianchi models
radiation_streaming_approximation = 3

# 3.3 - perturbations_sampling_stepsize:
# Default (0.1) is too large for low-ell multipoles (e.g., ell = 2)
perturbations_sampling_stepsize = 0.01

# 3.4 - Tight-coupling approximation parameters
tight_coupling_trigger_tau_c_over_tau_h = 0.005
start_small_omega_tau = 0.001
#tight_coupling_trigger_tau_c_over_tau_k = 0.005
#start_sources_at_tau_c_over_tau_h = 0.005

# 3.5 - Integration precision and related parameters
tol_perturbations_integration = 1.e-6 # Precision of the ndsolver
hyper_x_min = 1.0e-7 # The default is 1.0e-5, but it leads to lack of precision when the curvature is small

###############################################################################

# ---------------------------------------
# 4. Verbosity: standard output messages
# ---------------------------------------

# Increase integer values to make each module more talkative (default: all set to 0)

input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 2
transfer_verbose = 2
harmonic_verbose = 2
primordial_verbose = 1
spectra_verbose = 1
nonlinear_verbose = 1
lensing_verbose = 1
output_verbose = 1
